"""Added IsVerifyed and Canceled attributes to Ticket

Revision ID: 7d82a9943c67
Revises: c2be2e7e553d
Create Date: 2026-04-28 15:28:27.312896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d82a9943c67'
down_revision = 'c2be2e7e553d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('purchase_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_verified')
        batch_op.drop_column('is_cancelled')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
