"""Added missing movie fields

Revision ID: c2be2e7e553d
Revises: a7ab32609f88
Create Date: 2026-04-28 14:42:41.748861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2be2e7e553d'
down_revision = 'a7ab32609f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('pg', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('length', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('length')
        batch_op.drop_column('pg')
        batch_op.drop_column('rating')
        batch_op.drop_column('director')
        batch_op.drop_column('description')
        batch_op.drop_column('picture_path')

    # ### end Alembic commands ###
